import { BiLogoGit, BiLogoPostgresql } from "react-icons/bi";
import { DiVisualstudio } from "react-icons/di";
import {
  FaCss3,
  FaDocker,
  FaFigma,
  FaGithub,
  FaGitlab,
  FaGolang,
  FaHtml5,
  FaJava,
  FaJenkins,
  FaLinux,
  FaNodeJs,
  FaPython,
  FaReact,
  FaRust,
  FaSass,
  FaServer,
  FaWindows,
} from "react-icons/fa6";
import { IoLogoJavascript } from "react-icons/io5";
import {
  SiCsharp,
  SiGnubash,
  SiHono,
  SiMicrosoftsqlserver,
  SiMongodb,
  SiNextdotjs,
  SiPowershell,
  SiTypescript,
} from "react-icons/si";
import { VscVscode } from "react-icons/vsc";

export const SoftwareSkillsIcons = {
  "Next.js": SiNextdotjs,
  Java: FaJava,
  JavaScript: IoLogoJavascript,
  TypeScript: SiTypescript,
  "C#": SiCsharp,
  Rust: FaRust,
  Python: FaPython,
  Bash: SiGnubash,
  PowerShell: SiPowershell,
  Linux: FaLinux,
  Windows: FaWindows,
  React: FaReact,
  "Node.js": FaNodeJs,
  HTML5: FaHtml5,
  CSS3: FaCss3,
  SASS: FaSass,
  Express: FaServer,
  Hono: SiHono,
  Git: BiLogoGit,
  GitHub: FaGithub,
  GitLab: FaGitlab,
  Jenkins: FaJenkins,
  "Visual Studio": DiVisualstudio,
  VSCode: VscVscode,
  Figma: FaFigma,
  "SQL Server": SiMicrosoftsqlserver,
  PostgreSQL: BiLogoPostgresql,
  MongoDB: SiMongodb,
  Docker: FaDocker,
  Golang: FaGolang,
};
