import { BiLogoPostgresql } from "react-icons/bi";
import { DiMsqlServer } from "react-icons/di";
import {
  FaCss3,
  FaDocker,
  FaFigma,
  FaGithub,
  FaGitlab,
  FaGolang,
  FaHtml5,
  FaJava,
  FaJenkins,
  FaNodeJs,
  FaPython,
  FaReact,
  FaRust,
  FaSass,
} from "react-icons/fa6";
import { IoLogoJavascript } from "react-icons/io5";
import { RiTailwindCssFill } from "react-icons/ri";
import {
  SiGnubash,
  SiMongodb,
  SiNextdotjs,
  SiReactrouter,
  SiTypescript,
  SiVite,
} from "react-icons/si";
import { TbBrandCSharp, TbBrandPowershell } from "react-icons/tb";

export const SoftwareSkillsIcons = {
  "Node.js": FaNodeJs,
  Vite: SiVite,
  "React Router": SiReactrouter,
  Tailwind: RiTailwindCssFill,
  React: FaReact,
  "Next.js": SiNextdotjs,
  TypeScript: SiTypescript,
  JavaScript: IoLogoJavascript,
  Golang: FaGolang,
  // Express: FaServer,
  // Hono: SiHono,
  HTML5: FaHtml5,
  CSS3: FaCss3,
  SASS: FaSass,
  "C#": TbBrandCSharp,
  Java: FaJava,
  Rust: FaRust,
  Python: FaPython,
  // Git: BiLogoGit,
  GitHub: FaGithub,
  GitLab: FaGitlab,
  Jenkins: FaJenkins,
  // "Visual Studio": DiVisualstudio,
  // VSCode: VscVscode,
  Figma: FaFigma,
  "SQL Server": DiMsqlServer,
  PostgreSQL: BiLogoPostgresql,
  MongoDB: SiMongodb,
  Docker: FaDocker,
  Bash: SiGnubash,
  PowerShell: TbBrandPowershell,
  // Linux: FaLinux,
  // Windows: FaWindows,
};
